version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-lambda-sample"
s3_bucket = "rust-sandbox"
s3_prefix = "aws-lambda-sample"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
