AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SampleRustFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["arm64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: ../target/aarch64-unknown-linux-gnu/release/aws-lambda-sample

Outputs:
  FunctionName:
    Value: !Ref SampleRustFunction
    Description: sample