on:
  push:
    branches:
      - main
    paths:
      - 'aws-lambda-sample/**'
      - '.github/workflows/aws-lambda-sample.yml'

defaults:
  run:
    working-directory: './aws-lambda-sample'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: build
        run: 'cargo build'
      - name: test
        run: 'cargo test'
      - name: sam-build
        run: sam build --use-container
      - name: sam-deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name rust-lambda-sample --s3-bucket rust-sandbox --capabilities CAPABILITY_IAM --region ap-northeast-1